// Package consts provides constants for AspectGo.
package consts

// AutogenFileHeader is the header for auto-generated files.
const AutogenFileHeader = `// Automatically generated by aspectgo (https://golang.org/x/exp/aspectgo)
// DO NOT EDIT MANUALLY

`
